version: "3"

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - IMAGE_FRAMES_CSV_PATH=data/raw/image_data.csv
      - DATABASE_PATH=data/processed/image_data.db
